/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testprimitive_TestJNIPrimitive */

#ifndef _Included_testprimitive_TestJNIPrimitive
#define _Included_testprimitive_TestJNIPrimitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testprimitive_TestJNIPrimitive
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_testprimitive_TestJNIPrimitive_average
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     testprimitive_TestJNIPrimitive
 * Method:    transString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_testprimitive_TestJNIPrimitive_transString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     testprimitive_TestJNIPrimitive
 * Method:    sumAndAverage
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_testprimitive_TestJNIPrimitive_sumAndAverage
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     testprimitive_TestJNIPrimitive
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_testprimitive_TestJNIPrimitive_modifyInstanceVariable
  (JNIEnv *, jobject);

/*
 * Class:     testprimitive_TestJNIPrimitive
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_testprimitive_TestJNIPrimitive_nativeMethod
  (JNIEnv *, jobject);

/*
 * Class:     testprimitive_TestJNIPrimitive
 * Method:    sumAndAverageToo
 * Signature: ([Ljava/lang/Integer;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_testprimitive_TestJNIPrimitive_sumAndAverageToo
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     testprimitive_TestJNIPrimitive
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_testprimitive_TestJNIPrimitive_getIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
