/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_TestPackageJNI */

#ifndef _Included_myjni_TestPackageJNI
#define _Included_myjni_TestPackageJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_TestPackageJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_TestPackageJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
